name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '*/3 * * * *' # Trigger every 3 minutes
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Configure Git for commits
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      # Install yt-dlp
      - name: Install yt-dlp
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
          chmod +x yt-dlp
          sudo mv yt-dlp /usr/local/bin/

      # Fetch m3u8 for ma1
      - name: Generate ma1.m3u8
        run: |
          url=$(yt-dlp --print urls https://www.youtube.com/channel/UC1X2nRRWPptr88W_N9RWS1g/live)
          cat <<EOL > ma1.m3u8
          #EXTM3U
          #EXT-X-VERSION:3
          #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
          $url
          EOL

      # Fetch m3u8 for Dw
      - name: Generate Dw.m3u8
        run: |
          url=$(yt-dlp --print urls https://www.youtube.com/channel/UC30ditU5JI16o5NbFsHde_Q/live)
          cat <<EOL > Dw.m3u8
          #EXTM3U
          #EXT-X-VERSION:3
          #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
          $url
          EOL

      # Stage, commit, and push changes
      - name: Commit and Push Updates
        run: |
          git add .
          git commit -m "Updated m3u8 links [$(date)]"
          git push
        env:
          GIT_AUTHOR_NAME: "GitHub Action"
          GIT_AUTHOR_EMAIL: "action@github.com"
